name: Auto Invite Students

on:
  push:
    branches:
      - main

jobs:
  invite_students:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: NPM Install
      run: npm install

    - name: Send Invites
      run: node scripts/src/autoInviteStudents/script.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
